### ISSUE TITLE
yasiyosan don

### ISSUE THREAD

**Issue by nepinhum** [MrPl0ck/Kelime-Oyunu#1]
dayi yasiyon mu la

**Comment by MrPl0ck** [comment]
Aga sen kimsin

11 Tem 2023 Sal 04:53 tarihinde scher470 ***@***.***> şunu
yazdı:

**Comment by nxpinhum5326** [comment]
Ben furkan can messengerdan dcde kavga ettiydik karşılıklı engellledik sonra ulaşamadım sana bir daha hatırlarsın belki

**Comment by MrPl0ck** [comment]
Ya siktirgit orospu çocuğu ne sikime gelip de yaziyon

16 Tem 2023 Pzr 04:11 tarihinde scher470 ***@***.***> şunu
yazdı:

**Comment by nxpinhum5326** [comment]
Hala çocukluktan çıkamadın mı la sen :D neyse yine de baktığın için sağol.
